exclude: ^alembic/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: chart/|charts/|werf-*
      - id: end-of-file-fixer
        exclude: cred.json
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: [--autofix, --indent=2]
        exclude: cred.json

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        args: [-i]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args:
          [
            --ignore-missing-imports,
            --scripts-are-modules,
            --follow-imports=skip,
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
            --warn-redundant-casts,
            --implicit-optional,
            --exclude,
            site-packages,
          ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - darglint
          - dlint
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-isort
          - flake8-quotes

  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.3
    hooks:
      - id: pylint

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-q", "--ini", "setup.cfg"]
