[build]
dockerfilePath = "monolith/Dockerfile"
builder = "DOCKERFILE"

[deploy]
target = "production"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
