exclude: ^alembic/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-shebang-scripts-are-executable
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: detect-private-key
        exclude: cred.json
      - id: check-toml
      - id: check-merge-conflict
      - id: pretty-format-json
        args: [--autofix, --indent=2]
        exclude: cred.json
      - id: check-yaml
        exclude: chart/|charts/|werf-*
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: cred.json

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # unify removed due to Python 3.13 incompatibility (depends on lib2to3)

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--line-length=80, --skip-string-normalization]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - darglint
          - dlint
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-isort
          - flake8-quotes

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-q", "--ini", "setup.cfg"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        args:
          [
            --ignore-missing-imports,
            --scripts-are-modules,
            --follow-imports=skip,
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
            --warn-redundant-casts,
            --implicit-optional,
            --exclude,
            site-packages,
          ]
