[build]
dockerfilePath = "Dockerfile"
builder = "DOCKERFILE"

[deploy]
target = "production"
healthcheckPath = "/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
